"""Initial schema

Revision ID: 4f680d9f07c2
Revises: 
Create Date: 2025-11-10 22:36:21.741265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f680d9f07c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_aggregates',
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('class_id', 'window_start', 'window_end', 'metric_name')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_external_ref'), 'students', ['external_ref'], unique=False)
    op.create_table('assessments',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('assessed_on', sa.Date(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('empathy', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('adaptability', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('collaboration', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('communication', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('self_regulation', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('confidence_empathy', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confidence_adaptability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confidence_collaboration', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confidence_communication', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confidence_self_regulation', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_assessments_assessed_on'), 'assessments', ['assessed_on'], unique=False)
    op.create_index(op.f('ix_assessments_class_id'), 'assessments', ['class_id'], unique=False)
    op.create_index(op.f('ix_assessments_student_id'), 'assessments', ['student_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.Column('span_text', sa.Text(), nullable=False),
    sa.Column('span_location', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('score_contrib', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_assessment_id'), 'evidence', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_evidence_skill'), 'evidence', ['skill'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_skill'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_assessment_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_assessments_student_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_class_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessed_on'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_students_external_ref'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('class_aggregates')
    # ### end Alembic commands ###
